title: Corbin Featherstone | Graphic Designer
description: Senior Graphic Designer working in digital and print.

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js

url: https://corbin.nz
