title: Corbin Featherstone | Graphic Design & Brand Development
description: Senior Graphic Designer working in digital and print.
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml
url: https://corbin.nz
permalink: /:title
collections:
  work:
    output: true
    permalink: /:collection/:name
